### PR TITLE
Fix: Ensure search endpoint returns results in alphabetical order

### LINKED ISSUE #67: Make sure search endpont returns results in alphabetical order
Steps to reproduce

- Navigate to dmvboardgames.com and wait for the list of groups to appear

Expected result

- The "[Blood on the Clocktower at The Board and Brew](https://www.meetup.com/blood-on-the-clocktower-at-the-board-and-brew/) group is near the top of the list to maintain the alphabetical order.

Actual result

- The "[Blood on the Clocktower at The Board and Brew](https://www.meetup.com/blood-on-the-clocktower-at-the-board-and-brew/) group is at bottom of the list.

### PR DESCRIPTION
**Pull request by manishsahanidev**
Fix: This PR fixes a bug in the search endpoint to ensure that results are returned in alphabetical order.

Approach: Added an `ORDER BY groups.name ASC` clause to the `getQueryForAllResults()` method to ensure that results are sorted alphabetically by group name.

Closes #68

### CODE REVIEW

**Comment by UnknownOrange** [comment]
The query change looks good. Could you also add a test case to the following file that verifies that the SearchService getGroups function returns groups in alphabetical order?

https://github.com/Create-Third-Places/backend/blob/main/src/test/java/app/service/SearchServiceIntegrationTest.java

**Review by UnknownOrange — CHANGES_REQUESTED** [review]
The query change looks good. Could you also add a test case to the following file that verifies that the SearchService getGroups function returns groups in alphabetical order?

https://github.com/Create-Third-Places/backend/blob/main/src/test/java/app/service/SearchServiceIntegrationTest.java

**Comment by manishsahanidev** [comment]
Check now if something wrong tell me😄

**Review by UnknownOrange — CHANGES_REQUESTED** [review]

**Review by UnknownOrange — CHANGES_REQUESTED** [review]
Please refactor the the test to remove the .values() and toArray() methods on the following line: Group[] groups = result.getGroupData().values().toArray(new Group[0]);

They involve 2 extra loops that are unnecessary.

File: src/test/java/app/service/SearchServiceIntegrationTest.java [hunk 1]
```diff
@@ -208,4 +208,25 @@ public void testSearchResultReturnsValidResultWithExtraParameter()
     assertEquals(2, searchResult.countEvents());
     assertEquals(1, searchResult.countGroups());
   }
+
+  @Test
+  public void testGroupsAreOrderedAlphabetically() throws Exception {
+    LinkedHashMap<String, String> params = new LinkedHashMap<>();
+    GroupSearchResult result = searchService.getGroups(params, testConnectionProvider);
+
+    Iterator<Group> iterator = result.getGroupData().values().iterator();
```
Comment (UnknownOrange) [inline src/test/java/app/service/SearchServiceIntegrationTest.java:217]: Please remove the .values method and use a forEach to iterate through the array: https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html#forEach

**Review by UnknownOrange — CHANGES_REQUESTED** [review]

**Review by UnknownOrange — APPROVED** [review]
LGTM
